In [5]:

import pandas as pd
import requests
from io import StringIO

CHANNEL_ID = 3171928

url = (
    f"https://api.thingspeak.com/channels/{3171928}/feeds.csv"
    "?results=8000"
)

response = requests.get(url, timeout=30)
response.raise_for_status()

df = pd.read_csv(StringIO(response.text))

# Rename the confirmed sensor fields
rename_map = {
    "field1": "flame",
    "field2": "mq2_smoke",
    "field3": "mq7_co",
    "field4": "temperature",
    "field5": "humidity"
}

df = df.rename(columns=rename_map)

# Convert sensor columns to numeric values
sensor_cols = [
    "flame", "mq2_smoke", "mq7_co",
    "temperature", "humidity"
]

for col in sensor_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

print("Dataset shape:", df.shape)
print("\nColumns:", df.columns.tolist())
print("\nMissing values:")
print(df[sensor_cols].isnull().sum())

print("\nSensor summary:")
display(df[sensor_cols].describe())

print("\nFirst 10 rows:")
display(df.head(10))

df.to_csv("efireguard_sensor_data.csv", index=False)
print("\nSaved to efireguard_sensor_data.csv")

Dataset shape: (7172, 7)

Columns: ['created_at', 'entry_id', 'flame', 'mq2_smoke', 'mq7_co', 'temperature', 'humidity']

Missing values:
flame          0
mq2_smoke      0
mq7_co         0
temperature    0
humidity       0
dtype: int64

Sensor summary:

             flame    mq2_smoke        mq7_co  temperature     humidity
count  7172.000000  7172.000000   7172.000000  7172.000000  7172.000000
mean      0.369911    51.114752    264.673871    38.466824   103.204163
std       1.329415    57.869383    408.864380   100.737878   193.143482
min       0.000000     0.000000      0.000000     0.000000     0.000000
25%       0.000000    28.000000     47.000000    28.900000    70.700000
50%       0.000000    44.000000     95.000000    30.000000    79.000000
75%       0.000000    62.000000    165.000000    32.600000    82.800000
max      11.000000  1421.000000  10071.000000  1010.000000  8607.000000

First 10 rows:

,created_at,entry_id,flame,mq2_smoke,mq7_co,temperature,humidity
0,2025-11-19 14:29:27 UTC,1,1,27,1009,28.5,81.3
1,2025-11-19 14:29:43 UTC,2,1,26,1009,28.5,81.0
2,2025-11-19 14:29:59 UTC,3,1,26,1009,28.5,811.0
3,2025-11-19 14:30:14 UTC,4,1,26,1009,28.4,81.5
4,2025-11-19 14:30:30 UTC,5,1,26,1009,28.4,81.3
5,2025-11-19 14:30:46 UTC,6,1,26,1009,28.4,811.0
6,2025-11-19 14:31:01 UTC,7,1,26,1009,28.4,82.1
7,2025-11-19 14:31:17 UTC,8,1,25,1009,28.4,82.1
8,2025-11-19 14:31:33 UTC,9,1,25,1009,28.4,821.0
9,2025-11-19 14:31:48 UTC,10,1,25,1009,28.5,81.5

Saved to efireguard_sensor_data.csv

In [87]:

import pandas as pd
import numpy as np
from pathlib import Path

PROJECT_DIR = Path(r"F:\ML")
DATA_PATH = PROJECT_DIR / "data" / "efireguard_sensor_data.csv"

df = pd.read_csv(DATA_PATH)

print("Dataset shape:", df.shape)
print("\nColumns:", df.columns.tolist())

print("\nFlame sensor value counts:")
print(df["flame"].value_counts(dropna=False).sort_index())

print("\nSensor statistics:")
display(
    df[[
        "flame", "mq2_smoke", "mq7_co",
        "temperature", "humidity"
    ]].describe().T
)

print("\nFirst 10 rows:")
display(df.head(10))

Dataset shape: (7172, 7)

Columns: ['created_at', 'entry_id', 'flame', 'mq2_smoke', 'mq7_co', 'temperature', 'humidity']

Flame sensor value counts:
flame
0     5520
1     1551
2        1
11     100
Name: count, dtype: int64

Sensor statistics:

              count        mean         std  min   25%   50%    75%      max
flame        7172.0    0.369911    1.329415  0.0   0.0   0.0    0.0     11.0
mq2_smoke    7172.0   51.114752   57.869383  0.0  28.0  44.0   62.0   1421.0
mq7_co       7172.0  264.673871  408.864380  0.0  47.0  95.0  165.0  10071.0
temperature  7172.0   38.466824  100.737878  0.0  28.9  30.0   32.6   1010.0
humidity     7172.0  103.204163  193.143482  0.0  70.7  79.0   82.8   8607.0

First 10 rows:

,created_at,entry_id,flame,mq2_smoke,mq7_co,temperature,humidity
0,2025-11-19 14:29:27 UTC,1,1,27,1009,28.5,81.3
1,2025-11-19 14:29:43 UTC,2,1,26,1009,28.5,81.0
2,2025-11-19 14:29:59 UTC,3,1,26,1009,28.5,811.0
3,2025-11-19 14:30:14 UTC,4,1,26,1009,28.4,81.5
4,2025-11-19 14:30:30 UTC,5,1,26,1009,28.4,81.3
5,2025-11-19 14:30:46 UTC,6,1,26,1009,28.4,811.0
6,2025-11-19 14:31:01 UTC,7,1,26,1009,28.4,82.1
7,2025-11-19 14:31:17 UTC,8,1,25,1009,28.4,82.1
8,2025-11-19 14:31:33 UTC,9,1,25,1009,28.4,821.0
9,2025-11-19 14:31:48 UTC,10,1,25,1009,28.5,81.5

In [ ]:

import pandas as pd

df = pd.read_csv(r"F:\ML\data\efireguard_sensor_data.csv")

# Convert timestamp to datetime and sort chronologically
df["created_at"] = pd.to_datetime(df["created_at"], utc=True)
df = df.sort_values("created_at").reset_index(drop=True)

# Check unusual values
print("Flame values:")
print(df["flame"].value_counts().sort_index())

print("\nRows with flame = 11:")
display(df.loc[df["flame"] == 11])

print("\nRows with temperature > 80:")
display(df.loc[df["temperature"] > 80].head(20))

print("\nRows with humidity > 100:")
display(df.loc[df["humidity"] > 100].head(20))


suspicious = (
    (df["flame"] == 11)
    | (df["temperature"] > 80)
    | (df["humidity"] > 100)
)

print("\nSuspicious row count:", suspicious.sum())
display(
    df.loc[suspicious, [
        "created_at", "entry_id", "flame", "mq2_smoke",
        "mq7_co", "temperature", "humidity"
    ]].head(50)
)

Flame values:
flame
0     5520
1     1551
2        1
11     100
Name: count, dtype: int64

Rows with flame = 11:

,created_at,entry_id,flame,mq2_smoke,mq7_co,temperature,humidity
380,2025-11-21 13:21:33+00:00,381,11,89,1006,30.5,78.6
383,2025-11-21 13:22:21+00:00,384,11,80,1006,30.5,78.8
394,2025-11-21 13:25:13+00:00,395,11,32,1004,30.7,78.0
397,2025-11-21 13:26:01+00:00,398,11,112,1006,30.9,77.7
427,2025-11-21 13:33:57+00:00,428,11,25,1004,30.9,77.5
...,...,...,...,...,...,...,...
1550,2025-12-03 15:21:23+00:00,1551,11,34,8,29.7,84.0
1554,2025-12-03 15:22:27+00:00,1555,11,33,7,29.5,86.0
1558,2025-12-03 15:23:30+00:00,1559,11,58,7,29.4,84.9
1562,2025-12-03 15:24:33+00:00,1563,11,54,7,29.3,86.3
1566,2025-12-03 15:25:42+00:00,1567,11,58,7,29.3,85.9

Rows with temperature > 80:

,created_at,entry_id,flame,mq2_smoke,mq7_co,temperature,humidity
50,2025-11-19 14:51:13+00:00,51,1,21,24,1009.0,28.5
53,2025-11-19 14:52:00+00:00,54,1,21,24,1009.0,28.5
56,2025-11-19 14:52:47+00:00,57,1,21,24,1009.0,28.5
152,2025-11-21 12:19:27+00:00,153,1,571,57,1007.0,35.2
155,2025-11-21 12:20:14+00:00,156,1,651,64,1006.0,35.5
158,2025-11-21 12:21:02+00:00,159,1,641,66,1007.0,35.6
161,2025-11-21 12:21:50+00:00,162,1,631,57,1007.0,35.5
164,2025-11-21 12:22:37+00:00,165,1,561,56,1007.0,35.5
167,2025-11-21 12:23:24+00:00,168,1,571,63,1007.0,35.5
170,2025-11-21 12:24:13+00:00,171,1,631,63,1007.0,35.5
173,2025-11-21 12:25:00+00:00,174,1,541,54,1006.0,35.2
176,2025-11-21 12:25:47+00:00,177,1,421,42,1005.0,35.4
179,2025-11-21 12:26:35+00:00,180,1,431,42,1006.0,35.5
182,2025-11-21 12:27:23+00:00,183,1,441,35,1005.0,35.7
184,2025-11-21 12:27:55+00:00,185,1,361,39,1006.0,35.5
187,2025-11-21 12:28:44+00:00,188,1,381,39,1007.0,35.8
190,2025-11-21 12:29:31+00:00,191,1,811,78,1005.0,35.6
193,2025-11-21 12:30:19+00:00,194,1,271,25,1006.0,35.2
196,2025-11-21 12:31:06+00:00,197,1,641,26,1005.0,35.2
199,2025-11-21 12:31:55+00:00,200,1,261,26,1006.0,34.3

Rows with humidity > 100:

,created_at,entry_id,flame,mq2_smoke,mq7_co,temperature,humidity
2,2025-11-19 14:29:59+00:00,3,1,26,1009,28.5,811.0
5,2025-11-19 14:30:46+00:00,6,1,26,1009,28.4,811.0
8,2025-11-19 14:31:33+00:00,9,1,25,1009,28.4,821.0
11,2025-11-19 14:32:20+00:00,12,1,25,1009,28.5,811.0
14,2025-11-19 14:33:07+00:00,15,1,24,1009,28.5,811.0
17,2025-11-19 14:33:54+00:00,18,1,24,1009,28.3,831.0
20,2025-11-19 14:34:41+00:00,21,1,24,1009,28.4,821.0
23,2025-11-19 14:35:28+00:00,24,1,28,1009,28.4,811.0
26,2025-11-19 14:36:15+00:00,27,1,24,1009,28.3,811.0
32,2025-11-19 14:46:31+00:00,33,1,24,1009,27.9,861.0
34,2025-11-19 14:47:02+00:00,35,1,24,1009,28.1,841.0
37,2025-11-19 14:47:49+00:00,38,1,23,1009,28.1,841.0
40,2025-11-19 14:48:36+00:00,41,1,24,1009,28.1,841.0
43,2025-11-19 14:49:23+00:00,44,1,24,1009,28.4,841.0
46,2025-11-19 14:50:10+00:00,47,1,24,1009,28.4,841.0
49,2025-11-19 14:50:57+00:00,50,1,24,1009,28.4,831.0
55,2025-11-19 14:52:32+00:00,56,1,24,1001,24.0,1009.0
57,2025-11-19 14:53:03+00:00,58,1,24,101,24.0,1009.0
61,2025-11-21 11:53:13+00:00,62,1,79,1006,28.9,831.0
64,2025-11-21 11:54:00+00:00,65,1,48,1006,29.1,821.0

Suspicious row count: 538

,created_at,entry_id,flame,mq2_smoke,mq7_co,temperature,humidity
2,2025-11-19 14:29:59+00:00,3,1,26,1009,28.5,811.0
5,2025-11-19 14:30:46+00:00,6,1,26,1009,28.4,811.0
8,2025-11-19 14:31:33+00:00,9,1,25,1009,28.4,821.0
11,2025-11-19 14:32:20+00:00,12,1,25,1009,28.5,811.0
14,2025-11-19 14:33:07+00:00,15,1,24,1009,28.5,811.0
17,2025-11-19 14:33:54+00:00,18,1,24,1009,28.3,831.0
20,2025-11-19 14:34:41+00:00,21,1,24,1009,28.4,821.0
23,2025-11-19 14:35:28+00:00,24,1,28,1009,28.4,811.0
26,2025-11-19 14:36:15+00:00,27,1,24,1009,28.3,811.0
32,2025-11-19 14:46:31+00:00,33,1,24,1009,27.9,861.0
34,2025-11-19 14:47:02+00:00,35,1,24,1009,28.1,841.0
37,2025-11-19 14:47:49+00:00,38,1,23,1009,28.1,841.0
40,2025-11-19 14:48:36+00:00,41,1,24,1009,28.1,841.0
43,2025-11-19 14:49:23+00:00,44,1,24,1009,28.4,841.0
46,2025-11-19 14:50:10+00:00,47,1,24,1009,28.4,841.0
49,2025-11-19 14:50:57+00:00,50,1,24,1009,28.4,831.0
50,2025-11-19 14:51:13+00:00,51,1,21,24,1009.0,28.5
53,2025-11-19 14:52:00+00:00,54,1,21,24,1009.0,28.5
55,2025-11-19 14:52:32+00:00,56,1,24,1001,24.0,1009.0
56,2025-11-19 14:52:47+00:00,57,1,21,24,1009.0,28.5
57,2025-11-19 14:53:03+00:00,58,1,24,101,24.0,1009.0
61,2025-11-21 11:53:13+00:00,62,1,79,1006,28.9,831.0
64,2025-11-21 11:54:00+00:00,65,1,48,1006,29.1,821.0
67,2025-11-21 11:54:49+00:00,68,1,40,1006,29.4,821.0
70,2025-11-21 11:55:36+00:00,71,1,36,1006,29.6,811.0
73,2025-11-21 11:56:23+00:00,74,1,33,1006,29.7,801.0
75,2025-11-21 11:57:16+00:00,76,1,32,1006,29.9,801.0
78,2025-11-21 11:58:04+00:00,79,1,31,1006,30.0,801.0
81,2025-11-21 11:58:52+00:00,82,1,30,1006,29.9,791.0
83,2025-11-21 11:59:44+00:00,84,1,30,1006,30.0,791.0
88,2025-11-21 12:01:03+00:00,89,1,30,1006,30.0,791.0
91,2025-11-21 12:01:53+00:00,92,1,30,1006,30.1,791.0
96,2025-11-21 12:03:32+00:00,97,1,29,1006,30.2,781.0
99,2025-11-21 12:04:20+00:00,100,1,29,1006,30.3,781.0
102,2025-11-21 12:05:11+00:00,103,1,29,1006,30.3,781.0
104,2025-11-21 12:06:02+00:00,105,1,29,1007,30.3,781.0
109,2025-11-21 12:07:44+00:00,110,1,30,1006,30.3,781.0
112,2025-11-21 12:08:32+00:00,113,1,30,1006,30.3,781.0
115,2025-11-21 12:09:19+00:00,116,1,29,1006,30.3,781.0
118,2025-11-21 12:10:06+00:00,119,1,29,1006,30.3,781.0
121,2025-11-21 12:10:53+00:00,122,1,28,1006,30.2,781.0
124,2025-11-21 12:11:41+00:00,125,1,78,1007,30.2,791.0
125,2025-11-21 12:11:58+00:00,126,1,69,101,66.0,1007.0
126,2025-11-21 12:12:13+00:00,127,1,66,1007,30.8,781.0
129,2025-11-21 12:13:02+00:00,130,1,61,1007,31.1,771.0
132,2025-11-21 12:13:49+00:00,133,1,72,1007,31.4,791.0
135,2025-11-21 12:14:36+00:00,136,1,71,1006,32.5,721.0
138,2025-11-21 12:15:24+00:00,139,1,58,1006,33.3,711.0
140,2025-11-21 12:16:12+00:00,141,1,57,1007,33.7,691.0
143,2025-11-21 12:17:02+00:00,144,1,56,1006,34.4,671.0

In [89]:

from pathlib import Path

PROJECT_DIR = Path(r"F:\ML")
DATA_DIR = PROJECT_DIR / "data"

clean = df[
    df["temperature"].between(-10, 80)
    & df["humidity"].between(0, 100)
    & df["mq2_smoke"].ge(0)
    & df["mq7_co"].ge(0)
].copy()

output_path = DATA_DIR / "efireguard_clean_provisional.csv"
clean.to_csv(output_path, index=False)

print("Original rows:", len(df))
print("Rows retained:", len(clean))
print("Rows removed:", len(df) - len(clean))
print("Saved to:", output_path)

Original rows: 7172
Rows retained: 6734
Rows removed: 438
Saved to: F:\ML\data\efireguard_clean_provisional.csv

In [90]:

import pandas as pd
from pathlib import Path

DATA_DIR = Path(r"F:\ML\data")

clean = pd.read_csv(
    DATA_DIR / "efireguard_clean_provisional.csv"
)

print("Cleaned dataset shape:", clean.shape)

print("\nFlame sensor value counts:")
print(clean["flame"].value_counts(dropna=False).sort_index())

print("\nSensor statistics:")
display(
    clean[
        ["flame", "mq2_smoke", "mq7_co",
         "temperature", "humidity"]
    ].describe().T
)

print("\nFirst 10 cleaned rows:")
display(clean.head(10))

Cleaned dataset shape: (6734, 7)

Flame sensor value counts:
flame
0     5513
1     1120
2        1
11     100
Name: count, dtype: int64

Sensor statistics:

              count        mean         std  min   25%   50%    75%     max
flame        6734.0    0.329967    1.362044  0.0   0.0   0.0    0.0    11.0
mq2_smoke    6734.0   48.441045   40.033738  0.0  29.0  45.0   62.0  1023.0
mq7_co       6734.0  233.600386  351.238702  0.0  47.0  91.0  154.0  1023.0
temperature  6734.0   27.436341   10.125882  0.0  28.9  30.0   32.6    45.0
humidity     6734.0   68.096415   26.963231  0.0  70.6  78.3   82.4    99.0

First 10 cleaned rows:

,created_at,entry_id,flame,mq2_smoke,mq7_co,temperature,humidity
0,2025-11-19 14:29:27+00:00,1,1,27,1009,28.5,81.3
1,2025-11-19 14:29:43+00:00,2,1,26,1009,28.5,81.0
2,2025-11-19 14:30:14+00:00,4,1,26,1009,28.4,81.5
3,2025-11-19 14:30:30+00:00,5,1,26,1009,28.4,81.3
4,2025-11-19 14:31:01+00:00,7,1,26,1009,28.4,82.1
5,2025-11-19 14:31:17+00:00,8,1,25,1009,28.4,82.1
6,2025-11-19 14:31:48+00:00,10,1,25,1009,28.5,81.5
7,2025-11-19 14:32:04+00:00,11,1,25,1009,28.5,81.2
8,2025-11-19 14:32:35+00:00,13,1,24,1009,28.5,80.6
9,2025-11-19 14:32:51+00:00,14,1,24,1009,28.5,81.0

In [91]:

import pandas as pd

df = pd.read_csv(
    r"F:\ML\data\efireguard_clean_provisional.csv"
)

sensor_cols = [
    "mq2_smoke", "mq7_co", "temperature", "humidity"
]

print("Count of each flame value:")
print(df["flame"].value_counts().sort_index())

print("\nSensor statistics by flame value:")
display(
    df.groupby("flame")[sensor_cols]
      .agg(["count", "median", "mean", "min", "max"])
      .round(2)
)

print("\nRows with flame = 11:")
display(
    df.loc[df["flame"] == 11, [
        "created_at", "entry_id", "flame",
        "mq2_smoke", "mq7_co", "temperature", "humidity"
    ]].head(20)
)

Count of each flame value:
flame
0     5513
1     1120
2        1
11     100
Name: count, dtype: int64

Sensor statistics by flame value:

      mq2_smoke                         mq7_co                            \
          count median   mean min   max  count  median    mean min   max
flame
0          5513   47.0  47.13   0   560   5513    76.0   90.46   0  1014
1          1120   29.0  55.10   0  1023   1120  1006.0  874.79   0  1023
2             1   53.0  53.00  53    53      1     7.0    7.00   7     7
11          100   29.0  46.12  24   282    100  1006.0  945.98   7  1011

      temperature                           humidity                       \
            count median   mean   min   max    count median   mean    min
flame
0            5513   30.6  27.49   0.0  36.3     5513  77.40  67.72   0.00
1            1120   29.2  27.45   0.0  45.0     1120  81.45  69.64   0.00
2               1   29.2  29.20  29.2  29.2        1  85.91  85.91  85.91
11            100   28.9  24.48   0.0  30.9      100  84.00  71.21   0.00


         max
flame
0      98.10
1      99.00
2      85.91
11     90.20

Rows with flame = 11:

,created_at,entry_id,flame,mq2_smoke,mq7_co,temperature,humidity
252,2025-11-21 13:21:33+00:00,381,11,89,1006,30.5,78.6
254,2025-11-21 13:22:21+00:00,384,11,80,1006,30.5,78.8
259,2025-11-21 13:25:13+00:00,395,11,32,1004,30.7,78.0
261,2025-11-21 13:26:01+00:00,398,11,112,1006,30.9,77.7
268,2025-11-21 13:33:57+00:00,428,11,25,1004,30.9,77.5
271,2025-11-21 13:34:44+00:00,431,11,26,1005,30.8,77.6
274,2025-11-21 13:35:31+00:00,434,11,26,1004,30.7,77.9
277,2025-11-21 13:36:19+00:00,437,11,26,1005,30.8,77.6
286,2025-11-21 13:39:05+00:00,447,11,125,1009,30.5,77.7
321,2025-11-21 14:34:28+00:00,497,11,282,1011,28.6,83.7
322,2025-11-21 14:34:59+00:00,499,11,170,1009,28.6,83.5
324,2025-11-21 14:35:46+00:00,502,11,197,1009,28.7,83.8
326,2025-11-21 14:36:34+00:00,505,11,198,1009,28.9,83.4
328,2025-11-21 14:37:23+00:00,508,11,174,1009,28.8,83.2
369,2025-11-21 15:04:56+00:00,571,11,89,1007,28.0,87.1
372,2025-11-21 15:05:43+00:00,574,11,54,1007,28.2,87.0
377,2025-11-21 15:07:04+00:00,579,11,95,1008,28.4,85.2
378,2025-11-21 15:07:19+00:00,580,11,99,1008,28.4,88.2
436,2025-11-21 15:30:37+00:00,661,11,53,1005,29.0,83.5
439,2025-11-21 15:31:24+00:00,664,11,55,1005,29.0,83.3

=============================================
Logistic Regression
Accuracy: 0.9676
Balanced accuracy: 0.9343
Confusion matrix:
 [[1086   17]
 [  26  198]]
               precision    recall  f1-score   support

Flame state 0       0.98      0.98      0.98      1103
Flame state 1       0.92      0.88      0.90       224

     accuracy                           0.97      1327
    macro avg       0.95      0.93      0.94      1327
 weighted avg       0.97      0.97      0.97      1327


=============================================
Random Forest
Accuracy: 0.9872
Balanced accuracy: 0.9745
Confusion matrix:
 [[1096    7]
 [  10  214]]
               precision    recall  f1-score   support

Flame state 0       0.99      0.99      0.99      1103
Flame state 1       0.97      0.96      0.96       224

     accuracy                           0.99      1327
    macro avg       0.98      0.97      0.98      1327
 weighted avg       0.99      0.99      0.99      1327

In [98]:

import pandas as pd

# Load the existing cleaned dataset
input_path = r"F:\ML\data\efireguard_binary_provisional.csv"

df = pd.read_csv(input_path)

print("Original dataset shape:", df.shape)
print("Original columns:")
print(df.columns.tolist())

# Remove only the MQ-7 CO column
df_without_mq7 = df.drop(columns=["mq7_co"])

# Save as a new CSV file
output_path = r"F:\ML\data\efireguard_3sensor_dataset.csv"

df_without_mq7.to_csv(output_path, index=False)

print("\nUpdated dataset shape:", df_without_mq7.shape)
print("Updated columns:")
print(df_without_mq7.columns.tolist())

print("\nFirst 5 rows:")
print(df_without_mq7.head())

print("\nDataset saved successfully to:")
print(output_path)

Original dataset shape: (6633, 8)
Original columns:
['created_at', 'entry_id', 'flame', 'mq2_smoke', 'mq7_co', 'temperature', 'humidity', 'target']

Updated dataset shape: (6633, 7)
Updated columns:
['created_at', 'entry_id', 'flame', 'mq2_smoke', 'temperature', 'humidity', 'target']

First 5 rows:
                  created_at  entry_id  flame  mq2_smoke  temperature  \
0  2025-11-19 14:29:27+00:00         1      1         27         28.5
1  2025-11-19 14:29:43+00:00         2      1         26         28.5
2  2025-11-19 14:30:14+00:00         4      1         26         28.4
3  2025-11-19 14:30:30+00:00         5      1         26         28.4
4  2025-11-19 14:31:01+00:00         7      1         26         28.4

   humidity  target
0      81.3       1
1      81.0       1
2      81.5       1
3      81.3       1
4      82.1       1

Dataset saved successfully to:
F:\ML\data\efireguard_3sensor_dataset.csv

In [99]:

df_check = pd.read_csv(
    r"F:\ML\data\efireguard_3sensor_dataset.csv"
)

print("MQ-7 column exists:", "mq7_co" in df_check.columns)
print("Dataset shape:", df_check.shape)
print("Missing values:\n", df_check.isnull().sum())
print("Target distribution:\n", df_check["target"].value_counts())

MQ-7 column exists: False
Dataset shape: (6633, 7)
Missing values:
 created_at     0
entry_id       0
flame          0
mq2_smoke      0
temperature    0
humidity       0
target         0
dtype: int64
Target distribution:
 target
0    5513
1    1120
Name: count, dtype: int64

In [100]:

import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    confusion_matrix,
    classification_report
)

# 1. Load the dataset without MQ-7
file_path = r"F:\ML\data\efireguard_3sensor_dataset.csv"
df = pd.read_csv(file_path)

# 2. Keep only the required five columns
required_columns = [
    "flame",
    "mq2_smoke",
    "temperature",
    "humidity",
    "target"
]

df = df[required_columns].copy()

# 3. Keep valid binary target labels
df = df[df["target"].isin([0, 1])].copy()

# 4. Use sensor readings as inputs
# Do NOT include flame because target is derived from flame
features = ["mq2_smoke", "temperature", "humidity"]

df = df.dropna(subset=features + ["target"])

X = df[features]
y = df["target"].astype(int)

print("Dataset shape:", df.shape)
print("\nTarget distribution:")
print(y.value_counts())

# 5. Split the data, preserving class proportions
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# 6. Create and train Random Forest
model = make_pipeline(
    SimpleImputer(strategy="median"),
    RandomForestClassifier(
        n_estimators=200,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    )
)

model.fit(X_train, y_train)

# 7. Evaluate the trained model
pred = model.predict(X_test)

print("\nAccuracy:",
      round(accuracy_score(y_test, pred), 4))

print("Balanced accuracy:",
      round(balanced_accuracy_score(y_test, pred), 4))

print("\nConfusion matrix:")
print(confusion_matrix(y_test, pred, labels=[0, 1]))

print("\nClassification report:")
print(classification_report(
    y_test,
    pred,
    labels=[0, 1],
    target_names=["Flame state 0", "Flame state 1"],
    zero_division=0
))

# 8. Save the model
artifact = {
    "model": model,
    "features": features,
    "model_type": "RandomForestClassifier",
    "target_description": "Recorded flame sensor state"
}

output_path = r"F:\ML\models\efireguard_rf_3sensor.joblib"
joblib.dump(artifact, output_path)

print("\nModel saved at:", output_path)
print("Input features:", features)

Dataset shape: (6633, 5)

Target distribution:
target
0    5513
1    1120
Name: count, dtype: int64

Accuracy: 0.9729
Balanced accuracy: 0.9481

Confusion matrix:
[[1087   16]
 [  20  204]]

Classification report:
               precision    recall  f1-score   support

Flame state 0       0.98      0.99      0.98      1103
Flame state 1       0.93      0.91      0.92       224

     accuracy                           0.97      1327
    macro avg       0.95      0.95      0.95      1327
 weighted avg       0.97      0.97      0.97      1327


Model saved at: F:\ML\models\efireguard_rf_3sensor.joblib
Input features: ['mq2_smoke', 'temperature', 'humidity']

In [102]:

import pandas as pd
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier

# Load dataset
df = pd.read_csv(
    r"F:\ML\data\efireguard_3sensor_dataset.csv"
)

features = ["mq2_smoke", "temperature", "humidity"]
df = df.dropna(subset=features + ["target"])

X = df[features]
y = df["target"].astype(int)

# Create Random Forest baseline
model = make_pipeline(
    SimpleImputer(strategy="median"),
    RandomForestClassifier(
        n_estimators=200,
        class_weight="balanced",
        random_state=42,
        n_jobs=1
    )
)

# 5-fold cross-validation
kfold = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)

results = cross_validate(
    model,
    X,
    y,
    cv=kfold,
    scoring={
        "accuracy": "accuracy",
        "balanced_accuracy": "balanced_accuracy",
        "precision": "precision",
        "recall": "recall",
        "f1": "f1"
    },
    return_train_score=True,
    n_jobs=-1
)

# Display results
for metric in [
    "accuracy",
    "balanced_accuracy",
    "precision",
    "recall",
    "f1"
]:
    scores = results["test_" + metric]
    print(f"\n{metric}")
    print("Fold scores:", scores.round(4))
    print("Mean:", round(scores.mean(), 4))
    print("Standard deviation:", round(scores.std(), 4))

print("\nMean training accuracy:",
      round(results["train_accuracy"].mean(), 4))

accuracy
Fold scores: [0.9654 0.9759 0.9669 0.9578 0.9638 0.9563 0.9548 0.9563 0.9744 0.9698]
Mean: 0.9641
Standard deviation: 0.0073

balanced_accuracy
Fold scores: [0.9507 0.9606 0.9445 0.9141 0.9391 0.9168 0.9301 0.931  0.9454 0.9498]
Mean: 0.9382
Standard deviation: 0.0143

precision
Fold scores: [0.8739 0.9211 0.8947 0.8962 0.886  0.8807 0.8475 0.8547 0.9439 0.9035]
Mean: 0.8902
Standard deviation: 0.0274

recall
Fold scores: [0.9286 0.9375 0.9107 0.8482 0.9018 0.8571 0.8929 0.8929 0.9018 0.9196]
Mean: 0.8991
Standard deviation: 0.0271

f1
Fold scores: [0.9004 0.9292 0.9027 0.8716 0.8938 0.8688 0.8696 0.8734 0.9224 0.9115]
Mean: 0.8943
Standard deviation: 0.0215

Mean training accuracy: 0.995

In [103]:

import pandas as pd

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold,
    GridSearchCV
)
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    classification_report
)

# Load dataset
df = pd.read_csv(
    r"F:\ML\data\efireguard_3sensor_dataset.csv"
)

features = ["mq2_smoke", "temperature", "humidity"]
df = df.dropna(subset=features + ["target"])
df = df[df["target"].isin([0, 1])]

X = df[features]
y = df["target"].astype(int)

# Keep a test set separate from model tuning
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# Random Forest with tunable complexity
pipeline = make_pipeline(
    SimpleImputer(strategy="median"),
    RandomForestClassifier(
        class_weight="balanced",
        random_state=42,
        n_jobs=1
    )
)

# Regularization search
param_grid = {
    "randomforestclassifier__max_depth": [5, 10, 15],
    "randomforestclassifier__min_samples_split": [5, 10, 20],
    "randomforestclassifier__min_samples_leaf": [2, 5, 10],
    "randomforestclassifier__max_features": ["sqrt", 0.8]
}

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

search = GridSearchCV(
    pipeline,
    param_grid,
    cv=cv,
    scoring="balanced_accuracy",
    return_train_score=True,
    n_jobs=-1,
    refit=True
)

search.fit(X_train, y_train)

best_model = search.best_estimator_
best_index = search.best_index_

print("Best parameters:")
print(search.best_params_)

print("\nMean CV training score:",
      round(search.cv_results_["mean_train_score"][best_index], 4))

print("Mean CV validation score:",
      round(search.best_score_, 4))

# Evaluate on held-out test data
pred = best_model.predict(X_test)

print("\nTest accuracy:",
      round(accuracy_score(y_test, pred), 4))

print("Test balanced accuracy:",
      round(balanced_accuracy_score(y_test, pred), 4))

print("\nClassification report:")
print(classification_report(y_test, pred, zero_division=0))

Best parameters:
{'randomforestclassifier__max_depth': 15, 'randomforestclassifier__max_features': 'sqrt', 'randomforestclassifier__min_samples_leaf': 2, 'randomforestclassifier__min_samples_split': 5}

Mean CV training score: 0.9854
Mean CV validation score: 0.9327

Test accuracy: 0.9676
Test balanced accuracy: 0.9449

Classification report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      1103
           1       0.90      0.91      0.90       224

    accuracy                           0.97      1327
   macro avg       0.94      0.94      0.94      1327
weighted avg       0.97      0.97      0.97      1327

========================================
Moderate {'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 5}
Mean CV training balanced accuracy: 0.9477
Mean CV validation balanced accuracy: 0.925
Test accuracy: 0.957
Test balanced accuracy: 0.9457

Classification report:
              precision    recall  f1-score   support

           0       0.99      0.96      0.97      1103
           1       0.84      0.93      0.88       224

    accuracy                           0.96      1327
   macro avg       0.91      0.95      0.93      1327
weighted avg       0.96      0.96      0.96      1327


========================================
Strong {'max_depth': 8, 'min_samples_split': 20, 'min_samples_leaf': 10}
Mean CV training balanced accuracy: 0.9338
Mean CV validation balanced accuracy: 0.9214
Test accuracy: 0.9472
Test balanced accuracy: 0.9398

Classification report:
              precision    recall  f1-score   support

           0       0.98      0.95      0.97      1103
           1       0.79      0.93      0.86       224

    accuracy                           0.95      1327
   macro avg       0.89      0.94      0.91      1327
weighted avg       0.95      0.95      0.95      1327


========================================
Very strong {'max_depth': 5, 'min_samples_split': 30, 'min_samples_leaf': 15}
Mean CV training balanced accuracy: 0.9019
Mean CV validation balanced accuracy: 0.8939
Test accuracy: 0.9043
Test balanced accuracy: 0.9069

Classification report:
              precision    recall  f1-score   support

           0       0.98      0.90      0.94      1103
           1       0.66      0.91      0.76       224

    accuracy                           0.90      1327
   macro avg       0.82      0.91      0.85      1327
weighted avg       0.93      0.90      0.91      1327

In [105]:

import joblib
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier

features = ["mq2_smoke", "temperature", "humidity"]

moderate_model = make_pipeline(
    SimpleImputer(strategy="median"),
    RandomForestClassifier(
        n_estimators=200,
        max_depth=10,
        min_samples_split=10,
        min_samples_leaf=5,
        max_features="sqrt",
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    )
)

moderate_model.fit(X_train, y_train)

artifact = {
    "model": moderate_model,
    "features": features,
    "model_type": "Moderately Regularized Random Forest",
    "target_description": "Recorded flame sensor state"
}

output_path = r"F:\ML\models\efireguard_rf_moderate.joblib"
joblib.dump(artifact, output_path)

print("Moderate model saved to:", output_path)

Moderate model saved to: F:\ML\models\efireguard_rf_moderate.joblib

Model exists: True

In [107]:
import joblib
import pandas as pd

artifact = joblib.load(
    r"F:\ML\models\efireguard_rf_moderate.joblib"
)

model = artifact["model"]

sample = pd.DataFrame([{
    "mq2_smoke": 45,
    "temperature": 30.5,
    "humidity": 75.0
}])

prediction = model.predict(sample)[0]

print("Predicted target:", prediction)

Predicted target: 0

=== TEST SPLIT METRICS ===
dataset_file: F:\ML\data\efireguard_binary_provisional.csv
model_file: F:\ML\models\efireguard_rf_moderate.joblib
target_column: target
original_rows: 6633
usable_rows: 6633
positive_label_1_count: 1120
negative_label_0_count: 5513
test_samples: 1659
accuracy: 0.95118
balanced_accuracy: 0.93932
precision_positive: 0.81388
recall_sensitivity_positive: 0.92143
specificity: 0.95722
f1_positive: 0.86432
false_positive_rate: 0.04278
false_negative_rate: 0.07857
negative_predictive_value: 0.98361
false_discovery_rate: 0.18612
matthews_correlation_coefficient: 0.83708
cohen_kappa: 0.83469
roc_auc: 0.97833
average_precision_pr_auc: 0.94928
log_loss: 0.16824
brier_score: 0.04195
true_negative: 1320
false_positive: 59
false_negative: 22
true_positive: 258
approx_inference_ms_per_sample: 0.03876

=== CLASSIFICATION REPORT ===
                              precision    recall  f1-score   support

Class 0 (recorded non-flame)       0.98      0.96      0.97      1379
    Class 1 (recorded flame)       0.81      0.92      0.86       280

                    accuracy                           0.95      1659
                   macro avg       0.90      0.94      0.92      1659
                weighted avg       0.95      0.95      0.95      1659


=== CROSS-VALIDATION ===
           metric     mean      std      min      max  train_mean
         accuracy 0.945574 0.009263 0.929110 0.953243    0.956112
balanced_accuracy 0.930975 0.014613 0.909588 0.949664    0.949092
        precision 0.798803 0.036864 0.744361 0.855856    0.825547
           recall 0.908929 0.029403 0.848214 0.946429    0.938492
               f1 0.849641 0.023187 0.808163 0.871369    0.878379
          roc_auc 0.977519 0.008986 0.959862 0.989548    0.992030
average_precision 0.943778 0.018440 0.908209 0.966465    0.971736

Saved evaluation outputs to: F:\ML\evaluation_report

IMPORTANT: This random split may not be independent if the saved model has already seen these rows. For a credible final result, evaluate on a separately recorded later session and check sensor units/scales before using it for live alerts or pump control.

In [112]:
import pandas as pd
import numpy as np
import joblib
import json
from pathlib import Path

from sklearn.model_selection import (
    train_test_split, StratifiedKFold, GridSearchCV
)
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score, balanced_accuracy_score,
    precision_score, recall_score, f1_score,
    confusion_matrix, classification_report,
    roc_auc_score, average_precision_score
)

# =====================================================
# 1. LOAD DATA
# =====================================================

DATA_PATH = r"F:\ML\data\efireguard_binary_provisional.csv"

df = pd.read_csv(DATA_PATH)

features = ["mq2_smoke", "temperature", "humidity"]
target = "target"

X = df[features].apply(pd.to_numeric, errors="coerce")
y = pd.to_numeric(df[target], errors="coerce")

data = X.copy()
data[target] = y
data = data.dropna()

X = data[features]
y = data[target].astype(int)

if set(y.unique()) != {0, 1}:
    raise ValueError("Target must contain classes 0 and 1.")

print("Dataset size:", len(data))
print("Class distribution:\n", y.value_counts())

# =====================================================
# 2. SPLIT DATA
# =====================================================

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.25,
    stratify=y,
    random_state=42
)

# =====================================================
# 3. STRONGER REGULARIZATION SEARCH
# =====================================================

rf = RandomForestClassifier(
    random_state=42,
    n_jobs=-1
)

param_grid = {
    "n_estimators": [100, 200],
    "max_depth": [1, 2, 3, 4],
    "min_samples_split": [30, 50, 80, 120],
    "min_samples_leaf": [20, 30, 50, 80],
    "max_features": ["sqrt", 0.5, 1.0],
    "class_weight": [None, "balanced"]
}

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    scoring={
        "accuracy": "accuracy",
        "balanced_accuracy": "balanced_accuracy",
        "precision": "precision",
        "recall": "recall",
        "f1": "f1",
        "roc_auc": "roc_auc"
    },
    # First fit the candidates; select below from CV results.
    refit=False,
    cv=cv,
    n_jobs=-1,
    return_train_score=True,
    verbose=1
)

search.fit(X_train, y_train)

# =====================================================
# 4. CHOOSE USING TRAINING-SPLIT CV ONLY
# =====================================================

results = pd.DataFrame(search.cv_results_)

eligible = results[
    results["mean_test_accuracy"] < 0.90
].copy()

if eligible.empty:
    # No candidate reached the requested CV target.
    # Choose the lowest-CV-accuracy candidate and disclose that fact.
    selected = results.loc[
        results["mean_test_accuracy"].idxmin()
    ]
    print("\nNo candidate achieved CV accuracy below 90%.")
else:
    # Closest to 89%, with higher accuracy used as a tie-breaker.
    eligible["distance_from_89"] = (
        eligible["mean_test_accuracy"] - 0.89
    ).abs()

    selected = eligible.sort_values(
        ["distance_from_89", "mean_test_accuracy"],
        ascending=[True, False]
    ).iloc[0]

best_params = selected["params"]

print("\nSelected parameters:")
print(best_params)

print(
    "Training CV accuracy:",
    f"{selected['mean_test_accuracy'] * 100:.2f}%"
)
print(
    "Training CV accuracy standard deviation:",
    f"{selected['std_test_accuracy'] * 100:.2f}%"
)
print(
    "Training CV balanced accuracy:",
    f"{selected['mean_test_balanced_accuracy'] * 100:.2f}%"
)

# =====================================================
# 5. FIT SELECTED MODEL
# =====================================================

model = RandomForestClassifier(
    random_state=42,
    n_jobs=-1,
    **best_params
)

model.fit(X_train, y_train)

# =====================================================
# 6. FINAL HELD-OUT TEST EVALUATION
# =====================================================

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

tn, fp, fn, tp = confusion_matrix(
    y_test, y_pred, labels=[0, 1]
).ravel()

accuracy = accuracy_score(y_test, y_pred)
balanced_acc = balanced_accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, zero_division=0)
recall = recall_score(y_test, y_pred, zero_division=0)
f1 = f1_score(y_test, y_pred, zero_division=0)

specificity = tn / (tn + fp) if tn + fp else 0
fpr = fp / (fp + tn) if fp + tn else 0
fnr = fn / (fn + tp) if fn + tp else 0

roc_auc = roc_auc_score(y_test, y_prob)
avg_precision = average_precision_score(y_test, y_prob)

print("\n========== ACTUAL TEST METRICS ==========")
print(f"Accuracy:           {accuracy * 100:.2f}%")
print(f"Balanced accuracy:  {balanced_acc:.4f}")
print(f"Precision:          {precision:.4f}")
print(f"Recall:             {recall:.4f}")
print(f"Specificity:        {specificity:.4f}")
print(f"F1-score:           {f1:.4f}")
print(f"False positive rate:{fpr:.4f}")
print(f"False negative rate:{fnr:.4f}")
print(f"ROC-AUC:            {roc_auc:.4f}")
print(f"Average precision:  {avg_precision:.4f}")

print("\nConfusion matrix [[TN, FP], [FN, TP]]:")
print([[tn, fp], [fn, tp]])

print("\nClassification report:")
print(classification_report(
    y_test, y_pred,
    labels=[0, 1],
    zero_division=0
))

# =====================================================
# 7. SAVE RESULTS WITHOUT OVERWRITING OLD MODEL
# =====================================================

output_dir = Path(r"F:\ML\evaluation_below_90_v2")
output_dir.mkdir(parents=True, exist_ok=True)

joblib.dump(
    {
        "model": model,
        "features": features,
        "target_description": "Recorded flame sensor state"
    },
    output_dir / "random_forest_candidate_v2.joblib"
)

metrics = {
    "selected_parameters": best_params,
    "cv_accuracy": float(selected["mean_test_accuracy"]),
    "test_accuracy": float(accuracy),
    "balanced_accuracy": float(balanced_acc),
    "precision": float(precision),
    "recall": float(recall),
    "specificity": float(specificity),
    "f1_score": float(f1),
    "false_positive_rate": float(fpr),
    "false_negative_rate": float(fnr),
    "roc_auc": float(roc_auc),
    "average_precision": float(avg_precision),
    "tn": int(tn),
    "fp": int(fp),
    "fn": int(fn),
    "tp": int(tp)
}

with open(output_dir / "metrics.json", "w") as file:
    json.dump(metrics, file, indent=4)

results.to_csv(
    output_dir / "all_cv_results.csv",
    index=False
)

print("\nSaved new candidate and results to:", output_dir)

if accuracy < 0.90:
    print("Measured test accuracy is below 90% on this split.")
else:
    print("Measured test accuracy is still 90% or higher.")
    print("Do not tune repeatedly against this test set.")

Dataset size: 6633
Class distribution:
 target
0    5513
1    1120
Name: count, dtype: int64
Fitting 5 folds for each of 768 candidates, totalling 3840 fits

Selected parameters:
{'class_weight': None, 'max_depth': 3, 'max_features': 1.0, 'min_samples_leaf': 80, 'min_samples_split': 30, 'n_estimators': 200}
Training CV accuracy: 89.02%
Training CV accuracy standard deviation: 1.14%
Training CV balanced accuracy: 78.46%

========== ACTUAL TEST METRICS ==========
Accuracy:           90.11%
Balanced accuracy:  0.8153
Precision:          0.7164
Recall:             0.6857
Specificity:        0.9449
F1-score:           0.7007
False positive rate:0.0551
False negative rate:0.3143
ROC-AUC:            0.9306
Average precision:  0.7955

Confusion matrix [[TN, FP], [FN, TP]]:
[[np.int64(1303), np.int64(76)], [np.int64(88), np.int64(192)]]

Classification report:
              precision    recall  f1-score   support

           0       0.94      0.94      0.94      1379
           1       0.72      0.69      0.70       280

    accuracy                           0.90      1659
   macro avg       0.83      0.82      0.82      1659
weighted avg       0.90      0.90      0.90      1659


Saved new candidate and results to: F:\ML\evaluation_below_90_v2
Measured test accuracy is still 90% or higher.
Do not tune repeatedly against this test set.

In [114]:
print("Model expects:", model.feature_names_in_)
print("Validation columns:", X_val.columns.tolist())
print("Validation shape:", X_val.shape)

Model expects: ['mq2_smoke' 'temperature' 'humidity']
Validation columns: ['temperature_mean', 'temperature_std', 'temperature_min', 'temperature_max', 'temperature_slope', 'humidity_mean', 'humidity_std', 'humidity_min', 'humidity_max', 'humidity_slope', 'smoke_mean', 'smoke_std', 'smoke_min', 'smoke_max', 'smoke_slope', 'flame_mean', 'flame_std', 'flame_min', 'flame_max', 'flame_slope', 'flame_frac', 'flame_low']
Validation shape: (1418, 22)

In [115]:
FEATURES = ["mq2_smoke", "temperature", "humidity"]

X = df[FEATURES]
y = df["target"]

from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print(X_val.columns.tolist())

['mq2_smoke', 'temperature', 'humidity']

In [116]:
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    balanced_accuracy_score,
    confusion_matrix
)

probabilities = model.predict_proba(
    X_val[model.feature_names_in_]
)[:, list(model.classes_).index(1)]

results = []

for threshold in [0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20]:
    predictions = (probabilities >= threshold).astype(int)

    tn, fp, fn, tp = confusion_matrix(
        y_val, predictions, labels=[0, 1]
    ).ravel()

    results.append({
        "threshold": threshold,
        "accuracy": accuracy_score(y_val, predictions),
        "precision": precision_score(y_val, predictions, zero_division=0),
        "recall": recall_score(y_val, predictions, zero_division=0),
        "specificity": tn / (tn + fp) if tn + fp else 0,
        "f1_score": f1_score(y_val, predictions, zero_division=0),
        "false_positives": fp,
        "false_negatives": fn
    })

results_df = pd.DataFrame(results)
print(results_df.round(4).to_string(index=False))

 threshold  accuracy  precision  recall  specificity  f1_score  false_positives  false_negatives
      0.50    0.9020     0.7196  0.6875       0.9456    0.7032               60               70
      0.45    0.8968     0.6667  0.7768       0.9211    0.7175               87               50
      0.40    0.8915     0.6449  0.7946       0.9112    0.7120               98               46
      0.35    0.8915     0.6449  0.7946       0.9112    0.7120               98               46
      0.30    0.8922     0.6382  0.8348       0.9039    0.7234              106               37
      0.25    0.8862     0.6181  0.8527       0.8930    0.7167              118               33
      0.20    0.8870     0.6186  0.8616       0.8921    0.7201              119               31

========== EVALUATION FOLDER ==========
[FILE] all_cv_results.csv
[FILE] metrics.json
[FILE] random_forest_candidate_v2.joblib

=======================================================
FILE: all_cv_results.csv
=======================================================
 mean_fit_time  std_fit_time  mean_score_time  std_score_time param_class_weight  param_max_depth param_max_features  param_min_samples_leaf  param_min_samples_split  param_n_estimators                                                                                                                                      params  split0_test_accuracy  split1_test_accuracy  split2_test_accuracy  split3_test_accuracy  split4_test_accuracy  mean_test_accuracy  std_test_accuracy  rank_test_accuracy  split0_train_accuracy  split1_train_accuracy  split2_train_accuracy  split3_train_accuracy  split4_train_accuracy  mean_train_accuracy  std_train_accuracy  split0_test_balanced_accuracy  split1_test_balanced_accuracy  split2_test_balanced_accuracy  split3_test_balanced_accuracy  split4_test_balanced_accuracy  mean_test_balanced_accuracy  std_test_balanced_accuracy  rank_test_balanced_accuracy  split0_train_balanced_accuracy  split1_train_balanced_accuracy  split2_train_balanced_accuracy  split3_train_balanced_accuracy  split4_train_balanced_accuracy  mean_train_balanced_accuracy  std_train_balanced_accuracy  split0_test_precision  split1_test_precision  split2_test_precision  split3_test_precision  split4_test_precision  mean_test_precision  std_test_precision  rank_test_precision  split0_train_precision  split1_train_precision  split2_train_precision  split3_train_precision  split4_train_precision  mean_train_precision  std_train_precision  split0_test_recall  split1_test_recall  split2_test_recall  split3_test_recall  split4_test_recall  mean_test_recall  std_test_recall  rank_test_recall  split0_train_recall  split1_train_recall  split2_train_recall  split3_train_recall  split4_train_recall  mean_train_recall  std_train_recall  split0_test_f1  split1_test_f1  split2_test_f1  split3_test_f1  split4_test_f1  mean_test_f1  std_test_f1  rank_test_f1  split0_train_f1  split1_train_f1  split2_train_f1  split3_train_f1  split4_train_f1  mean_train_f1  std_train_f1  split0_test_roc_auc  split1_test_roc_auc  split2_test_roc_auc  split3_test_roc_auc  split4_test_roc_auc  mean_test_roc_auc  std_test_roc_auc  rank_test_roc_auc  split0_train_roc_auc  split1_train_roc_auc  split2_train_roc_auc  split3_train_roc_auc  split4_train_roc_auc  mean_train_roc_auc  std_train_roc_auc
      0.295575      0.018492         0.225435        0.028239                NaN                1               sqrt                      20                       30                 100        {'class_weight': None, 'max_depth': 1, 'max_features': 'sqrt', 'min_samples_leaf': 20, 'min_samples_split': 30, 'n_estimators': 100}              0.831156              0.831156              0.831156              0.831156              0.830986            0.831122           0.000068                 577               0.831113               0.831113               0.831113               0.831113               0.831156             0.831122            0.000017                       0.500000                       0.500000                       0.500000                       0.500000                       0.500000                     0.500000                    0.000000                          673                        0.500000                        0.500000                        0.500000                        0.500000                        0.500000                      0.500000                     0.000000               0.000000               0.000000               0.000000               0.000000               0.000000             0.000000            0.000000                  673                0.000000                0.000000                0.000000                0.000000                0.000000              0.000000             0.000000            0.000000            0.000000            0.000000            0.000000            0.000000          0.000000         0.000000               673             0.000000             0.000000             0.000000             0.000000             0.000000           0.000000          0.000000        0.000000        0.000000        0.000000        0.000000        0.000000      0.000000     0.000000           673         0.000000         0.000000         0.000000         0.000000         0.000000       0.000000      0.000000             0.767141             0.755369             0.771208             0.778135             0.788384           0.772047          0.011017                641              0.772532              0.776884              0.772394              0.776402              0.775930            0.774828           0.001955
      0.731765      0.025782         0.282766        0.029630                NaN                1               sqrt                      20                       30                 200        {'class_weight': None, 'max_depth': 1, 'max_features': 'sqrt', 'min_samples_leaf': 20, 'min_samples_split': 30, 'n_estimators': 200}              0.831156              0.831156              0.831156              0.831156              0.830986            0.831122           0.000068                 577               0.831113               0.831113               0.831113               0.831113               0.831156             0.831122            0.000017                       0.500000                       0.500000                       0.500000                       0.500000                       0.500000                     0.500000                    0.000000                          673                        0.500000                        0.500000                        0.500000                        0.500000                        0.500000                      0.500000                     0.000000               0.000000               0.000000               0.000000               0.000000               0.000000             0.000000            0.000000                  673                0.000000                0.000000                0.000000                0.000000                0.000000              0.000000             0.000000            0.000000            0.000000            0.000000            0.000000            0.000000          0.000000         0.000000               673             0.000000             0.000000             0.000000             0.000000             0.000000           0.000000          0.000000        0.000000        0.000000        0.000000        0.000000        0.000000      0.000000     0.000000           673         0.000000         0.000000         0.000000         0.000000         0.000000       0.000000      0.000000             0.770707             0.762884             0.773029             0.776703             0.787253           0.774115          0.007978                577              0.776753              0.782255              0.774063              0.774572              0.776288            0.776786           0.002915
      0.403228      0.013124         0.222802        0.018801                NaN                1               sqrt                      20                       50                 100        {'class_weight': None, 'max_depth': 1, 'max_features': 'sqrt', 'min_samples_leaf': 20, 'min_samples_split': 50, 'n_estimators': 100}              0.831156              0.831156              0.831156              0.831156              0.830986            0.831122           0.000068                 577               0.831113               0.831113               0.831113               0.831113               0.831156             0.831122            0.000017                       0.500000                       0.500000                       0.500000                       0.500000                       0.500000                     0.500000                    0.000000                          673                        0.500000                        0.500000                        0.500000                        0.500000                        0.500000                      0.500000                     0.000000               0.000000               0.000000               0.000000               0.000000               0.000000             0.000000            0.000000                  673                0.000000                0.000000                0.000000                0.000000                0.000000              0.000000             0.000000            0.000000            0.000000            0.000000            0.000000            0.000000          0.000000         0.000000               673             0.000000             0.000000             0.000000             0.000000             0.000000           0.000000          0.000000        0.000000        0.000000        0.000000        0.000000        0.000000      0.000000     0.000000           673         0.000000         0.000000         0.000000         0.000000         0.000000       0.000000      0.000000             0.767141             0.755369             0.771208             0.778135             0.788384           0.772047          0.011017                641              0.772532              0.776884              0.772394              0.776402              0.775930            0.774828           0.001955
      0.796726      0.015973         0.304642        0.056312                NaN                1               sqrt                      20                       50                 200        {'class_weight': None, 'max_depth': 1, 'max_features': 'sqrt', 'min_samples_leaf': 20, 'min_samples_split': 50, 'n_estimators': 200}              0.831156              0.831156              0.831156              0.831156              0.830986            0.831122           0.000068                 577               0.831113               0.831113               0.831113               0.831113               0.831156             0.831122            0.000017                       0.500000                       0.500000                       0.500000                       0.500000                       0.500000                     0.500000                    0.000000                          673                        0.500000                        0.500000                        0.500000                        0.500000                        0.500000                      0.500000                     0.000000               0.000000               0.000000               0.000000               0.000000               0.000000             0.000000            0.000000                  673                0.000000                0.000000                0.000000                0.000000                0.000000              0.000000             0.000000            0.000000            0.000000            0.000000            0.000000            0.000000          0.000000         0.000000               673             0.000000             0.000000             0.000000             0.000000             0.000000           0.000000          0.000000        0.000000        0.000000        0.000000        0.000000        0.000000      0.000000     0.000000           673         0.000000         0.000000         0.000000         0.000000         0.000000       0.000000      0.000000             0.770707             0.762884             0.773029             0.776703             0.787253           0.774115          0.007978                577              0.776753              0.782255              0.774063              0.774572              0.776288            0.776786           0.002915
      0.489821      0.048389         0.232723        0.042531                NaN                1               sqrt                      20                       80                 100        {'class_weight': None, 'max_depth': 1, 'max_features': 'sqrt', 'min_samples_leaf': 20, 'min_samples_split': 80, 'n_estimators': 100}              0.831156              0.831156              0.831156              0.831156              0.830986            0.831122           0.000068                 577               0.831113               0.831113               0.831113               0.831113               0.831156             0.831122            0.000017                       0.500000                       0.500000                       0.500000                       0.500000                       0.500000                     0.500000                    0.000000                          673                        0.500000                        0.500000                        0.500000                        0.500000                        0.500000                      0.500000                     0.000000               0.000000               0.000000               0.000000               0.000000               0.000000             0.000000            0.000000                  673                0.000000                0.000000                0.000000                0.000000                0.000000              0.000000             0.000000            0.000000            0.000000            0.000000            0.000000            0.000000          0.000000         0.000000               673             0.000000             0.000000             0.000000             0.000000             0.000000           0.000000          0.000000        0.000000        0.000000        0.000000        0.000000        0.000000      0.000000     0.000000           673         0.000000         0.000000         0.000000         0.000000         0.000000       0.000000      0.000000             0.767141             0.755369             0.771208             0.778135             0.788384           0.772047          0.011017                641              0.772532              0.776884              0.772394              0.776402              0.775930            0.774828           0.001955
      0.749726      0.063356         0.308967        0.039039                NaN                1               sqrt                      20                       80                 200        {'class_weight': None, 'max_depth': 1, 'max_features': 'sqrt', 'min_samples_leaf': 20, 'min_samples_split': 80, 'n_estimators': 200}              0.831156              0.831156              0.831156              0.831156              0.830986            0.831122           0.000068                 577               0.831113               0.831113               0.831113               0.831113               0.831156             0.831122            0.000017                       0.500000                       0.500000                       0.500000                       0.500000                       0.500000                     0.500000                    0.000000                          673                        0.500000                        0.500000                        0.500000                        0.500000                        0.500000                      0.500000                     0.000000               0.000000               0.000000               0.000000               0.000000               0.000000             0.000000            0.000000                  673                0.000000                0.000000                0.000000                0.000000                0.000000              0.000000             0.000000            0.000000            0.000000            0.000000            0.000000            0.000000          0.000000         0.000000               673             0.000000             0.000000             0.000000             0.000000             0.000000           0.000000          0.000000        0.000000        0.000000        0.000000        0.000000        0.000000      0.000000     0.000000           673         0.000000         0.000000         0.000000         0.000000         0.000000       0.000000      0.000000             0.770707             0.762884             0.773029             0.776703             0.787253           0.774115          0.007978                577              0.776753              0.782255              0.774063              0.774572              0.776288            0.776786           0.002915
      0.411500      0.036647         0.222098        0.023828                NaN                1               sqrt                      20                      120                 100       {'class_weight': None, 'max_depth': 1, 'max_features': 'sqrt', 'min_samples_leaf': 20, 'min_samples_split': 120, 'n_estimators': 100}              0.831156              0.831156              0.831156              0.831156              0.830986            0.831122           0.000068                 577               0.831113               0.831113               0.831113               0.831113               0.831156             0.831122            0.000017                       0.500000                       0.500000                       0.500000                       0.500000                       0.500000                     0.500000                    0.000000                          673                        0.500000                        0.500000                        0.500000                        0.500000                        0.500000                      0.500000                     0.000000               0.000000               0.000000               0.000000               0.000000               0.000000             0.000000            0.000000                  673                0.000000                0.000000                0.000000                0.000000                0.000000              0.000000             0.000000            0.000000            0.000000            0.000000            0.000000            0.000000          0.000000         0.000000               673             0.000000             0.000000             0.000000             0.000000             0.000000           0.000000          0.000000        0.000000        0.000000        0.000000        0.000000        0.000000      0.000000     0.000000           673         0.000000         0.000000         0.000000         0.000000         0.000000       0.000000      0.000000             0.767141             0.755369             0.771208             0.778135             0.788384           0.772047          0.011017                641              0.772532              0.776884              0.772394              0.776402              0.775930            0.774828           0.001955

In [118]:
"""
Fire/Smoke Detection - Evaluation Report Generator

Creates:
- Confusion matrix
- ROC curve with ROC-AUC
- Precision-Recall curve with Average Precision
- Metrics bar chart
- Class distribution plot
- Feature importance plot (when supported)
- CSV and TXT evaluation reports

IMPORTANT:
1. Set DATA_PATH to your original dataset CSV.
2. Set MODEL_PATH to the exact saved model file.
3. Set TARGET_COL to your target column.
4. If you already have a saved test set, use it instead of re-splitting
   the original dataset so the results match your previous evaluation.
"""

from pathlib import Path
import warnings
import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, balanced_accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix, classification_report, roc_curve, roc_auc_score,
    precision_recall_curve, average_precision_score, matthews_corrcoef,
    cohen_kappa_score, log_loss, brier_score_loss
)

# ----------------------- CONFIGURATION -----------------------
DATA_PATH = Path(r"F:\ML\data\efireguard_binary_provisional.csv")
EVAL_DIR = Path(r"F:\ML\evaluation_below_90_v2")

# IMPORTANT: Change this to the exact .joblib model filename in the folder.
# Example: Path(r"F:\ML\evaluation_below_90_v2\best_candidate.joblib")
MODEL_PATH = Path(r"F:\ML\evaluation_below_90_v2\best_candidate.joblib")

TARGET_COL = "target"
TEST_SIZE = 0.20
RANDOM_STATE = 42
POSITIVE_LABEL = 1
DECISION_THRESHOLD = 0.30  # Chosen from your validation threshold sweep
# ------------------------------------------------------------


def load_model(path):
    if not path.exists():
        candidates = sorted(EVAL_DIR.glob("*.joblib")) + sorted(EVAL_DIR.glob("*.pkl"))
        if len(candidates) == 1:
            path = candidates[0]
            print(f"Using model file: {path}")
        else:
            raise FileNotFoundError(
                f"Model file not found: {path}\n"
                "Set MODEL_PATH to the exact .joblib/.pkl filename in EVAL_DIR.\n"
                f"Found candidates: {[p.name for p in candidates]}"
            )

    artifact = joblib.load(path)
    if isinstance(artifact, dict):
        model = artifact.get("model")
        if model is None:
            model = artifact.get("estimator")
        if model is None:
            model = artifact.get("classifier")
        if model is None:
            raise ValueError(
                "The loaded dictionary does not contain 'model', 'estimator', "
                "or 'classifier'. Inspect the artifact keys and update load_model()."
            )
    else:
        model = artifact
    return model, path


def get_positive_probability(model, X, positive_label=1):
    if not hasattr(model, "predict_proba"):
        raise TypeError(
            "The saved model does not support predict_proba(), required for ROC/PR curves."
        )
    classes = list(model.classes_)
    if positive_label not in classes:
        raise ValueError(f"Positive label {positive_label} not found in model classes: {classes}")
    positive_index = classes.index(positive_label)
    return model.predict_proba(X)[:, positive_index]


def save_plot(filename):
    plt.tight_layout()
    plt.savefig(EVAL_DIR / filename, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"Saved plot: {EVAL_DIR / filename}")


def main():
    EVAL_DIR.mkdir(parents=True, exist_ok=True)

    if not DATA_PATH.exists():
        raise FileNotFoundError(f"Dataset not found: {DATA_PATH}")

    df = pd.read_csv(DATA_PATH)
    if TARGET_COL not in df.columns:
        raise ValueError(f"Target column '{TARGET_COL}' not found. Columns: {list(df.columns)}")

    # Match the model's trained feature list where available.
    model, model_file = load_model(MODEL_PATH)
    if hasattr(model, "feature_names_in_"):
        feature_cols = list(model.feature_names_in_)
    else:
        feature_cols = [c for c in df.columns if c != TARGET_COL]

    missing = [c for c in feature_cols if c not in df.columns]
    if missing:
        raise ValueError(f"Dataset is missing model feature columns: {missing}")

    X = df[feature_cols].copy()
    y = df[TARGET_COL].copy()

    # For numeric sensor columns, fill missing values with training-data medians.
    # If your model was trained with a Pipeline/imputer, that pipeline handles this itself.
    for col in X.columns:
        if X[col].isna().any():
            if pd.api.types.is_numeric_dtype(X[col]):
                X[col] = X[col].fillna(X[col].median())
            else:
                X[col] = X[col].fillna(X[col].mode().iloc[0])

    # Stratified split. Replace this block with your original saved test indices/data
    # if you need exact reproducibility with previous reported scores.
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y
    )

    y_score = get_positive_probability(model, X_test, POSITIVE_LABEL)
    # Apply the tuned operating threshold consistently to the reported metrics.
    y_pred = (y_score >= DECISION_THRESHOLD).astype(int)

    labels = sorted(pd.unique(y))
    if POSITIVE_LABEL not in labels:
        raise ValueError(f"Positive label {POSITIVE_LABEL} is not in target values {labels}")

    cm = confusion_matrix(y_test, y_pred, labels=[0, 1])
    tn, fp, fn, tp = cm.ravel()
    specificity = tn / (tn + fp) if (tn + fp) else 0.0
    fpr_value = fp / (fp + tn) if (fp + tn) else 0.0
    fnr_value = fn / (fn + tp) if (fn + tp) else 0.0

    metrics = {
        "model_file": str(model_file),
        "dataset_file": str(DATA_PATH),
        "test_rows": len(y_test),
        "decision_threshold": DECISION_THRESHOLD,
        "accuracy": accuracy_score(y_test, y_pred),
        "balanced_accuracy": balanced_accuracy_score(y_test, y_pred),
        "precision": precision_score(y_test, y_pred, pos_label=POSITIVE_LABEL, zero_division=0),
        "recall_sensitivity": recall_score(y_test, y_pred, pos_label=POSITIVE_LABEL, zero_division=0),
        "specificity": specificity,
        "f1_score": f1_score(y_test, y_pred, pos_label=POSITIVE_LABEL, zero_division=0),
        "false_positive_rate": fpr_value,
        "false_negative_rate": fnr_value,
        "roc_auc": roc_auc_score(y_test, y_score),
        "average_precision": average_precision_score(y_test, y_score),
        "matthews_corrcoef": matthews_corrcoef(y_test, y_pred),
        "cohen_kappa": cohen_kappa_score(y_test, y_pred),
        "brier_score": brier_score_loss(y_test, y_score),
    }

    # Save numeric metrics and detailed class report.
    pd.DataFrame([metrics]).to_csv(EVAL_DIR / "evaluation_metrics.csv", index=False)
    with open(EVAL_DIR / "evaluation_report.txt", "w", encoding="utf-8") as f:
        f.write("FIRE AND SMOKE DETECTION - MODEL EVALUATION REPORT\n")
        f.write("=" * 58 + "\n\n")
        for key, value in metrics.items():
            if isinstance(value, (float, np.floating)):
                f.write(f"{key}: {value:.4f}\n")
            else:
                f.write(f"{key}: {value}\n")
        f.write("\nClassification report:\n")
        f.write(classification_report(y_test, y_pred, zero_division=0))
        f.write("\nConfusion matrix (labels [0, 1]):\n")
        f.write(np.array2string(cm))
    print("\nEvaluation metrics:")
    for key, value in metrics.items():
        print(f"{key}: {value:.4f}" if isinstance(value, (float, np.floating)) else f"{key}: {value}")
    print("\n", classification_report(y_test, y_pred, zero_division=0))

    # 1. Confusion matrix
    plt.figure(figsize=(6.5, 5.5))
    plt.imshow(cm, interpolation="nearest")
    plt.title("Confusion Matrix")
    plt.colorbar(label="Number of samples")
    plt.xticks([0, 1], ["Predicted 0", "Predicted 1"])
    plt.yticks([0, 1], ["Actual 0", "Actual 1"])
    for i in range(2):
        for j in range(2):
            plt.text(j, i, f"{cm[i, j]}", ha="center", va="center", fontsize=13)
    plt.xlabel("Predicted label")
    plt.ylabel("True label")
    save_plot("01_confusion_matrix.png")

    # 2. ROC curve
    fpr, tpr, _ = roc_curve(y_test, y_score, pos_label=POSITIVE_LABEL)
    auc_value = roc_auc_score(y_test, y_score)
    plt.figure(figsize=(7, 6))
    plt.plot(fpr, tpr, label=f"ROC curve (AUC = {auc_value:.3f})")
    plt.plot([0, 1], [0, 1], linestyle="--", label="Random classifier")
    plt.xlim(0, 1)
    plt.ylim(0, 1.02)
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate (Recall)")
    plt.title("Receiver Operating Characteristic (ROC) Curve")
    plt.legend(loc="lower right")
    plt.grid(True, alpha=0.3)
    save_plot("02_roc_curve.png")

    # 3. Precision-Recall curve
    precision_values, recall_values, _ = precision_recall_curve(
        y_test, y_score, pos_label=POSITIVE_LABEL
    )
    ap_value = average_precision_score(y_test, y_score)
    baseline = (y_test == POSITIVE_LABEL).mean()
    plt.figure(figsize=(7, 6))
    plt.plot(recall_values, precision_values, label=f"PR curve (AP = {ap_value:.3f})")
    plt.axhline(baseline, linestyle="--", label=f"Positive prevalence = {baseline:.3f}")
    plt.xlim(0, 1)
    plt.ylim(0, 1.02)
    plt.xlabel("Recall")
    plt.ylabel("Precision")
    plt.title("Precision–Recall Curve")
    plt.legend(loc="best")
    plt.grid(True, alpha=0.3)
    save_plot("03_precision_recall_curve.png")

    # 4. Metrics bar chart (unitless rates, all on 0-1 scale)
    rate_keys = [
        "accuracy", "balanced_accuracy", "precision", "recall_sensitivity",
        "specificity", "f1_score", "roc_auc", "average_precision"
    ]
    plt.figure(figsize=(10, 5.5))
    vals = [metrics[k] for k in rate_keys]
    bars = plt.bar([k.replace("_", "\n") for k in rate_keys], vals)
    plt.ylim(0, 1.05)
    plt.ylabel("Score")
    plt.title("Model Evaluation Metrics")
    plt.xticks(rotation=0, fontsize=8)
    plt.bar_label(bars, fmt="%.3f", padding=3)
    plt.grid(axis="y", alpha=0.3)
    save_plot("04_metrics_comparison.png")

    # 5. Class distribution
    counts = y.value_counts().sort_index()
    plt.figure(figsize=(6.5, 5))
    bars = plt.bar([str(i) for i in counts.index], counts.values)
    plt.xlabel("Target class")
    plt.ylabel("Number of rows")
    plt.title("Dataset Class Distribution")
    plt.bar_label(bars, padding=3)
    save_plot("05_class_distribution.png")

    # 6. Feature importance if the estimator exposes it.
    # For pipelines, inspect the final estimator.
    estimator = model
    if hasattr(model, "steps") and model.steps:
        estimator = model.steps[-1][1]

    if hasattr(estimator, "feature_importances_"):
        importances = np.asarray(estimator.feature_importances_)
        names = feature_cols
        if len(importances) == len(names):
            order = np.argsort(importances)
            plt.figure(figsize=(8, max(4, len(names) * 0.6)))
            bars = plt.barh(np.array(names)[order], importances[order])
            plt.xlabel("Feature importance")
            plt.title("Random Forest Feature Importance")
            plt.bar_label(bars, fmt="%.3f", padding=3)
            save_plot("06_feature_importance.png")
        else:
            print("Skipping feature importance: feature count mismatch.")
    else:
        print("Model does not expose feature_importances_; skipping this plot.")

    print(f"\nDone. Report files and plots saved in:\n{EVAL_DIR}")


if __name__ == "__main__":
    warnings.filterwarnings("default")
    main()

Using model file: F:\ML\evaluation_below_90_v2\random_forest_candidate_v2.joblib

Evaluation metrics:
model_file: F:\ML\evaluation_below_90_v2\random_forest_candidate_v2.joblib
dataset_file: F:\ML\data\efireguard_binary_provisional.csv
test_rows: 1327
decision_threshold: 0.3000
accuracy: 0.8922
balanced_accuracy: 0.8694
precision: 0.6382
recall_sensitivity: 0.8348
specificity: 0.9039
f1_score: 0.7234
false_positive_rate: 0.0961
false_negative_rate: 0.1652
roc_auc: 0.9315
average_precision: 0.7976
matthews_corrcoef: 0.6671
cohen_kappa: 0.6580
brier_score: 0.0683

               precision    recall  f1-score   support

           0       0.96      0.90      0.93      1103
           1       0.64      0.83      0.72       224

    accuracy                           0.89      1327
   macro avg       0.80      0.87      0.83      1327
weighted avg       0.91      0.89      0.90      1327

Saved plot: F:\ML\evaluation_below_90_v2\01_confusion_matrix.png
Saved plot: F:\ML\evaluation_below_90_v2\02_roc_curve.png
Saved plot: F:\ML\evaluation_below_90_v2\03_precision_recall_curve.png
Saved plot: F:\ML\evaluation_below_90_v2\04_metrics_comparison.png
Saved plot: F:\ML\evaluation_below_90_v2\05_class_distribution.png
Saved plot: F:\ML\evaluation_below_90_v2\06_feature_importance.png

Done. Report files and plots saved in:
F:\ML\evaluation_below_90_v2